---
title: "Ensembles and Uplifting Modeling"
author: "Joshi Villagomwz"
date: "1/28/2020"
output:
  word_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

#### libraries
```{r}
library(adabag)
library(rpart) 
library(caret)

bank.df <- read.csv("~/Desktop/UniversalBank.csv")
bank.df <- bank.df[ , -c(1, 5)]  # Drop ID and zip code columns.
```
# transform Personal.Loan into categorical variable
```{r}
bank.df$Personal.Loan = as.factor(bank.df$Personal.Loan)

# partition the data
train.index <- sample(c(1:dim(bank.df)[1]), dim(bank.df)[1]*0.6)  
train.df <- bank.df[train.index, ]
valid.df <- bank.df[-train.index, ]
```
# single tree
```{r}
tr <- rpart(Personal.Loan ~ ., data = train.df)
pred <- predict(tr, valid.df, type = "class")
confusionMatrix(pred, valid.df$Personal.Loan)
```
# bagging
```{r}
bag <- bagging(Personal.Loan ~ ., data = train.df)
pred <- predict(bag, valid.df, type = "class")
confusionMatrix(as.factor(pred$class), valid.df$Personal.Loan)
```
# boosting
```{r}
boost <- boosting(Personal.Loan ~ ., data = bank.df)
pred <- predict(boost, valid.df, type = "class")
confusionMatrix(as.factor(pred$class), valid.df$Personal.Loan)
```


#### Voter Persuasion
```{r}
library(uplift)
voter.df <- read.csv("~/Desktop/Voter-Persuasion.csv")
# transform variable MOVED_AD to numerical
voter.df$MOVED_AD_NUM <- ifelse(voter.df$MOVED_AD == "Y", 1, 0)

set.seed(1)  
train.index <- sample(c(1:dim(voter.df)[1]), dim(voter.df)[1]*0.6)  
train.df <- voter.df[train.index, ]
valid.df <- voter.df[-train.index, ]
```
# use upliftRF to apply a Random Forest (alternatively use upliftKNN() to apply kNN). 
```{r}
up.fit <- upliftRF(MOVED_AD_NUM ~ AGE + NH_WHITE + COMM_PT + H_F1 + REG_DAYS+ 
                     PR_PELIG + E_PELIG + POLITICALC  + trt(MESSAGE_A),
                   data = train.df, mtry = 3, ntree = 100, split_method = "KL",
                   minsplit = 200, verbose = TRUE)
pred <- predict(up.fit, newdata = valid.df)
```
# first colunm: p(y | treatment) 
# second colunm: p(y | control) 
```{r}
head(data.frame(pred, "uplift" = pred[,1] - pred[,2]))
```
